# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    apache: 
      repo: "git@github.com:puppetlabs/puppetlabs-apache.git"
      ref: "v12.0.2"
    stdlib:
      repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
      ref: "v9.4.1"
    concat:
      repo: "git@github.com:puppetlabs/puppetlabs-concat.git"
      ref: "v9.0.2"