# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache: 
      repo: "puppetlabs/apache"
      ref: "12.0.2"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.4.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "9.0.2"
